### ISSUE TITLE
Strange format of rate representing

### ISSUE THREAD

**Issue by pechinkin** [Zylex-Dev/exchange-rate-telegram-bot#9]
Today i received a couple of alerts which included a rate but in e form (where e represents a degree of 10). It is well known among programmers but they are not the only users!

**Comment by pechinkin** [comment]
photo proof: ![image](https://github.com/user-attachments/assets/7241c15c-edc0-41c1-ae96-2c03247f34ad)

**Comment by Zylex-Dev** [comment]
Thank you for your issue, this problem has already been resolved - [commit](https://github.com/Zylex-Dev/exchange-rate-telegram-bot/commit/57eef8933ba354d3876b89fd53373105472aa5bf)

**Comment by pechinkin** [comment]
ok now i see the difference ![image](https://github.com/user-attachments/assets/3eb8d07a-ef97-45bf-ac05-c139b6d3c2c4)
